version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_healthy
      web:
        condition: service_started
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    expose:
      - "3000"
    environment:
      - API_URL=http://api:4000
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    expose:
      - "4000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - CORS_ORIGIN=http://localhost
      - API_HOST=localhost
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 1h
      timeout: 30s
      retries: 3
      start_period: 1m

  db:
    image: postgres:16-alpine
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: